spring.application.name=diasync

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger

diasync.database.cleanup.days-to-keep=360
diasync.database.cleanup.interval=PT1H

demo.userId=demo
demo.prefill.interval=PT72H

diasync.api.read-page-size=2000
diasync.api.long-poll-max-results=2000
diasync.api.long-poll-max-timeout-ms=90000
diasync.api.max-write-batch-size=2000

spring.jpa.open-in-view=false
